Fix bug which was killing all smoke-tests
 - only fail if there is no secret password

diff --git a/bin/circle-test-smoke b/bin/circle-test-smoke
--- a/bin/circle-test-smoke
+++ b/bin/circle-test-smoke
@@ -5,7 +5,7 @@ set -e
 source "$STATE"
 
 if [ -n "$TEST_AND_PUBLISH" ] ; then
-    [ -n "$SECRET_PASSWORD" ] || echo "Cannot run smoke tests: no secret key" && exit 1
+    [ -n "$SECRET_PASSWORD" ] || { echo "Cannot run smoke tests: no secret key"; exit 1; }
     cd $SRCDIR/test
     eval $(./gce.sh hosts)
     export COVERAGE=true
