don't allow lightweight tags after all

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -10,8 +10,8 @@ RELEASE_DESCRIPTION="Weaving Containers into Applications"
 
 setup() {
     ## Get the new version number from the most recent tag
-    if ! LATEST_TAG=$(git describe --tags --abbrev=0 --match='v*' 2>/dev/null) ; then
-        echo "Could not find a 'v*' version tag." >&2
+    if ! LATEST_TAG=$(git describe --abbrev=0 --match='v*' 2>/dev/null) ; then
+        echo "Could not find an annotated 'v*' version tag." >&2
         exit 1
     fi
     LATEST_TAG_SHA=$(git rev-parse $LATEST_TAG)
