cosmetic

diff --git a/weave b/weave
--- a/weave
+++ b/weave
@@ -1041,13 +1041,13 @@ case "$COMMAND" in
         if [ -z "$IPRANGE_SPECIFIED" ] ; then
             IPRANGE="10.128.0.0/10"
             if command_exists netcheck && ! netcheck $IPRANGE ; then
-                echo "ERROR: Default -iprange $IPRANGE overlaps with existing route." >&2
+                echo "ERROR: Default -iprange $IPRANGE overlaps with existing route on host." >&2
                 echo "You must pick another range and set it on all hosts." >&2
                 exit 1
             fi
         else
             if command_exists netcheck && ! netcheck $IPRANGE ; then
-                echo "WARNING: Specified -iprange $IPRANGE overlaps with existing route." >&2
+                echo "WARNING: Specified -iprange $IPRANGE overlaps with existing route on host." >&2
                 echo "Unless this is deliberate, you must pick another range and set it on all hosts." >&2
             fi
         fi
