cosmetic

diff --git a/weave b/weave
--- a/weave
+++ b/weave
@@ -789,15 +789,6 @@ add_iface_bridged_fastdp() {
     add_iface_bridge "$@"
 }
 
-ask_version() {
-    if ! DOCKERIMAGE=$(docker inspect --format='{{.Image}}' $1 2>/dev/null) ; then
-            if ! DOCKERIMAGE=$(docker inspect --format='{{.Id}}' $2 2>/dev/null) ; then
-                echo "Unable to find $2 image." >&2
-            fi
-    fi
-    [ -n "$DOCKERIMAGE" ] && docker run --rm --net=none -e WEAVE_CIDR=none $3 $DOCKERIMAGE $COVERAGE_ARGS --version
-}
-
 router_opts_fastdp() {
     echo "--datapath $DATAPATH"
 }
@@ -808,6 +799,15 @@ router_opts_bridge() {
 
 router_opts_bridged_fastdp() {
     router_opts_fastdp "$@"
+}
+
+ask_version() {
+    if ! DOCKERIMAGE=$(docker inspect --format='{{.Image}}' $1 2>/dev/null) ; then
+            if ! DOCKERIMAGE=$(docker inspect --format='{{.Id}}' $2 2>/dev/null) ; then
+                echo "Unable to find $2 image." >&2
+            fi
+    fi
+    [ -n "$DOCKERIMAGE" ] && docker run --rm --net=none -e WEAVE_CIDR=none $3 $DOCKERIMAGE $COVERAGE_ARGS --version
 }
 
 ######################################################################
