Remove CONTAINER_ARGS indirection

diff --git a/weave b/weave
--- a/weave
+++ b/weave
@@ -940,48 +940,55 @@ detach() {
 ######################################################################
 
 args_match() {
-    dummy_container=$(docker create $CONTAINER_ARGS)
+    prev_args="$(docker inspect -f '{{.Args}}' $1)"
+    shift
+    dummy_container=$(docker create "$@")
     dummy_args="$(docker inspect -f '{{.Args}}' $dummy_container)"
     docker rm $dummy_container >/dev/null
-    [ "$(docker inspect -f '{{.Args}}' $1)" = "$dummy_args" ]
+    [ "$prev_args"  = "$dummy_args" ]
 }
 
-# Check if a container for component $1 named $2 with image $3 is running, and start it if necessary
+# Check if a container for component $1 named $2 with image $3 and args $4... is running,
+# and start it if necessary
 start_if_necessary() {
-    RUN_STATUS=$(docker inspect --format='{{.State.Running}} {{.State.Status}} {{.Config.Image}} {{.Id}}' $2 2>/dev/null) || true
+    component=$1
+    name=$2
+    image=$3
+    shift 3
+    RUN_STATUS=$(docker inspect --format='{{.State.Running}} {{.State.Status}} {{.Config.Image}} {{.Id}}' $name 2>/dev/null) || true
     CONTAINER_ID=${RUN_STATUS##* }
     case ${RUN_STATUS%:*} in
-        "true restarting $3")
-            echo "$2 is restarting; you can stop it with 'weave stop-$1'." >&2
+        "true restarting $image")
+            echo "$name is restarting; you can stop it with 'weave stop-$component'." >&2
             return 3
             ;;
-        "true "*" $3")
-            if args_match $CONTAINER_ID ; then
+        "true "*" $image")
+            if args_match $CONTAINER_ID "$@" ; then
                 ALREADY_RUNNING_ID=$CONTAINER_ID
                 echo $CONTAINER_ID
             else
-                echo "$2 is already running with different arguments; you can stop it with 'weave stop-$1'." >&2
+                echo "$name is already running with different arguments; you can stop it with 'weave stop-$component'." >&2
                 return 1
             fi
             ;;
-        "false "*" $3")
-            if args_match $CONTAINER_ID ; then
+        "false "*" $image")
+            if args_match $CONTAINER_ID "$@" ; then
                 docker start $CONTAINER_ID
             else
-                docker rm $2 >/dev/null
-                docker run -d --name=$2 $CONTAINER_ARGS
+                docker rm $name >/dev/null
+                docker run -d --name=$name "$@"
             fi
             ;;
         true*)
-            echo "Found another running container named '$2'. Aborting." >&2
+            echo "Found another running container named '$name'. Aborting." >&2
             return 2
             ;;
         false*)
-            docker rm $2 >/dev/null
-            docker run -d --name=$2 $CONTAINER_ARGS
+            docker rm $name >/dev/null
+            docker run -d --name=$name "$@"
             ;;
         "")
-            docker run -d --name=$2 $CONTAINER_ARGS
+            docker run -d --name=$name "$@"
             ;;
     esac
 }
@@ -1614,7 +1621,8 @@ launch_router() {
     # Set WEAVE_DOCKER_ARGS in the environment in order to supply
     # additional parameters, such as resource limits, to docker
     # when launching the weave container.
-    CONTAINER_ARGS=$(echo --privileged --net=host \
+    ROUTER_CONTAINER=$(start_if_necessary router $CONTAINER_NAME $BASE_IMAGE \
+        --privileged --net=host \
         $(docker_sock_options) \
         -e WEAVE_PASSWORD \
         -e WEAVE_CIDR=none \
@@ -1626,7 +1634,6 @@ launch_router() {
         $DNS_ROUTER_OPTS $NO_DNS_OPT \
         --http-addr $HTTP_ADDR \
         "$@")
-    ROUTER_CONTAINER=$(start_if_necessary router $CONTAINER_NAME $BASE_IMAGE)
     [ -n "$ALREADY_RUNNING_ID" ] && return 0
     setup_router_iface_$BRIDGE_TYPE
     attach_router
@@ -1672,7 +1679,8 @@ launch_proxy() {
        docker create -v /w -v /w-noop -v /w-nomcast --name=$VOLUMES_CONTAINER_NAME \
            --label=weavevolumes --entrypoint=/bin/false $EXEC_IMAGE >/dev/null
     fi
-    CONTAINER_ARGS=$(echo --privileged --net=host \
+    PROXY_CONTAINER=$(start_if_necessary proxy $PROXY_CONTAINER_NAME $BASE_EXEC_IMAGE \
+        --privileged --net=host \
         $PROXY_VOLUMES \
         --volumes-from $VOLUMES_CONTAINER_NAME \
         $(docker_sock_options) \
@@ -1686,7 +1694,6 @@ launch_proxy() {
         -e EXEC_IMAGE=$EXEC_IMAGE \
         --entrypoint=/home/weave/weaveproxy \
         $WEAVEPROXY_DOCKER_ARGS $EXEC_IMAGE $COVERAGE_ARGS $PROXY_ARGS)
-    PROXY_CONTAINER=$(start_if_necessary proxy $PROXY_CONTAINER_NAME $BASE_EXEC_IMAGE)
     wait_for_status $PROXY_CONTAINER_NAME http_call_unix $PROXY_CONTAINER_NAME status.sock
 }
 
@@ -1696,17 +1703,14 @@ stop_proxy() {
 }
 
 launch_plugin_if_not_running() {
-    CONTAINER_ARGS=$(echo --privileged \
+    PLUGIN_CONTAINER=$(start_if_necessary plugin $PLUGIN_CONTAINER_NAME $BASE_PLUGIN_IMAGE \
+        --privileged \
         --restart=always \
         --net=host \
         $(docker_sock_options) \
         -v /run/docker/plugins:/run/docker/plugins \
         -e WEAVE_HTTP_ADDR \
         $PLUGIN_IMAGE "$@")
-
-    if ! PLUGIN_CONTAINER=$(start_if_necessary plugin $PLUGIN_CONTAINER_NAME $BASE_PLUGIN_IMAGE) ; then
-        return 1
-    fi
     wait_for_status $PLUGIN_CONTAINER_NAME http_call_unix $PLUGIN_CONTAINER_NAME status.sock
     util_op create-plugin-network weave weavemesh
 }
