zettio/weave#224 - moved all the rendezvous stuff to a separate container that will invoke "connects" in the Weave reorganized some code and cleaned up...

diff --git a/weave b/weave
--- a/weave
+++ b/weave
@@ -8,6 +8,7 @@ usage() {
     echo "weave setup"
     echo "weave launch     [-password <password> | -passwordfile <path>] <peer> ..."
     echo "weave launch-dns <cidr>"
+    echo "weave launch-rendezvous"
     echo "weave connect    <peer>"
     echo "weave run        [--with-dns] <cidr> <docker run args> ..."
     echo "weave start      <cidr> <container_id>"
@@ -44,18 +45,22 @@ IMAGE_VERSION=${VERSION:-$IMAGE_VERSION}
 
 BASE_IMAGE=zettio/weave
 BASE_DNS_IMAGE=zettio/weavedns
+BASE_RENDEZVOUS_IMAGE=zettio/weaverendezvous
 BASE_TOOLS_IMAGE=zettio/weavetools
 IMAGE=$BASE_IMAGE:$IMAGE_VERSION
 DNS_IMAGE=$BASE_DNS_IMAGE:$IMAGE_VERSION
+RENDEZVOUS_IMAGE=$BASE_RENDEZVOUS_IMAGE:$IMAGE_VERSION
 TOOLS_IMAGE=$BASE_TOOLS_IMAGE:$IMAGE_VERSION
 CONTAINER_NAME=weave
 DNS_CONTAINER_NAME=weavedns
+RENDEZVOUS_CONTAINER_NAME=weaverendezvous
 BRIDGE=weave
 CONTAINER_IFNAME=ethwe
 MTU=65535
 PORT=6783
 HTTP_PORT=6784
 DNS_HTTP_PORT=6785
+RENDEZVOUS_HTTP_PORT=6786
 DOCKER_BRIDGE=${DOCKER_BRIDGE:-docker0}
 
 COMMAND=$1
@@ -86,22 +91,6 @@ validate_cidr() {
         echo "CIDR must of be of form <ip_address>/<routing_prefix_length>, e.g. 10.0.1.1/24" >&2
         exit 1
     fi
-}
-
-dev_ip() {
-	ip addr show $1 | sed -n '/inet /{s/^.*inet \([0-9.]\+\).*$/\1/;p}' 2>/dev/null
-}
-
-is_using_mdns() {
-    echo "$@" | grep 'mdns\:\/\/' >/dev/null
-}
-
-host_ext_ips() {
-    # guess the possible external IP addresses...
-    EXT_DEVS=$(netstat -i | tail -n +3 | cut -f1 -d' ' | grep -v "^\(veth\|weave\|bridge\|docker\|lo\)")
-    EXT_IPS=""
-    for DEV in $EXT_DEVS ; do EXT_IPS="$EXT_IPS,$(dev_ip $DEV)" ; done
-    echo $EXT_IPS | cut -c2-
 }
 
 run_iptables() {
@@ -226,9 +215,9 @@ with_container_netns () {
 
 connect_container_to_bridge() {
     if [ "$(readlink /proc/$CONTAINER_PID/ns/net)" = "$(readlink /proc/$$/ns/net)" ] ; then
-        echo "WARNING: Container is running in the host network namespace, and therefore cannot be" >&2
-        echo "WARNING: connected to weave. Perhaps the container was started with --net=host." >&2
-        #return 1
+        echo "Container is running in the host network namespace, and therefore cannot be" >&2
+        echo "connected to weave. Perhaps the container was started with --net=host." >&2
+        return 1
     fi
     if ! ip link add name $LOCAL_IFNAME mtu $MTU type veth peer name $GUEST_IFNAME mtu $MTU ; then
         return 1
@@ -495,21 +484,13 @@ case "$COMMAND" in
             shift 2
         fi
 
-        DOCKER_NET_ARG=
-        WEAVE_EXT_ARGS=
-		if is_using_mdns $@ ; then
-			# get access to host's devices, so we can use mDNS's multicast
-			DOCKER_NET_ARG="--net=host"
-        	WEAVE_EXT_ARGS="-ext $(host_ext_ips)"
-        fi
-
         # Set WEAVE_DOCKER_ARGS in the environment in order to supply
         # additional parameters, such as resource limits, to docker
         # when launching the weave container.
         CONTAINER=$(docker run --privileged -d --name=$CONTAINER_NAME \
-            -p $PORT:$PORT/tcp -p $PORT:$PORT/udp $DOCKER_NET_ARG \
+            -p $PORT:$PORT/tcp -p $PORT:$PORT/udp \
             ${PASSWORD:+-e WEAVE_PASSWORD="$PASSWORD"} ${PASSWORDFILE:+--env-file="$PASSWORDFILE"} \
-            $WEAVE_DOCKER_ARGS $IMAGE -name $MACADDR -iface $CONTAINER_IFNAME $WEAVE_EXT_ARGS "$@")
+            $WEAVE_DOCKER_ARGS $IMAGE -name $MACADDR -iface $CONTAINER_IFNAME "$@")
         with_container_netns $CONTAINER launch >/dev/null
         echo $CONTAINER
         ;;
@@ -527,9 +508,28 @@ case "$COMMAND" in
         populate_dns
         echo $DNS_CONTAINER
         ;;
+    launch-rendezvous)
+        [ $# -gt 0 ] || usage
+        check_not_running $RENDEZVOUS_CONTAINER_NAME $BASE_RENDEZVOUS_IMAGE
+        create_bridge
+        docker_bridge_ip
+        RENDEZVOUS_CONTAINER=$(docker run --privileged -d --name=$RENDEZVOUS_CONTAINER_NAME \
+            -p $DOCKER_BRIDGE_IP:80:80/tcp --net=host \
+            $DNS_IMAGE -iface $CONTAINER_IFNAME "$@")
+        echo $RENDEZVOUS_CONTAINER
+        ;;
     connect)
         [ $# -eq 1 ] || usage
-        http_call $CONTAINER_NAME $HTTP_PORT POST /connect -d "peer=$1"
+        SCHEME=$(echo "$1" | grep :// | sed -e's,^\(.*://\).*,\1,g')
+        case "$SCHEME" in
+            "tcp://"|"")
+                http_call $CONTAINER_NAME $HTTP_PORT POST /connect -d "peer=$1"
+                ;;
+            *)
+                check_not_running $RENDEZVOUS_CONTAINER_NAME $BASE_RENDEZVOUS_IMAGE && $0 launch-rendezvous
+                http_call $RENDEZVOUS_CONTAINER_NAME $RENDEZVOUS_HTTP_PORT POST /connect -d "domain=$1"
+                ;;
+        esac
         ;;
     status)
         http_call $CONTAINER_NAME $HTTP_PORT GET /status
@@ -549,6 +549,7 @@ case "$COMMAND" in
         echo weave script $SCRIPT_VERSION
         ask_version $CONTAINER_NAME $IMAGE
         ask_version $DNS_CONTAINER_NAME $DNS_IMAGE
+        ask_version $RENDEZVOUS_CONTAINER_NAME $RENDEZVOUS_IMAGE
         if ! TOOLS_IMAGE_ID=$(docker inspect --format='{{ .Id }}' $TOOLS_IMAGE 2>/dev/null) ; then
             echo "Unable to find $TOOLS_IMAGE image." >&2
         else
@@ -653,10 +654,12 @@ case "$COMMAND" in
         ;;
     reset)
         [ $# -eq 0 ] || usage
-        docker kill  $CONTAINER_NAME     >/dev/null 2>&1 || true
-        docker kill  $DNS_CONTAINER_NAME >/dev/null 2>&1 || true
-        docker rm -f $CONTAINER_NAME     >/dev/null 2>&1 || true
-        docker rm -f $DNS_CONTAINER_NAME >/dev/null 2>&1 || true
+        docker kill  $CONTAINER_NAME            >/dev/null 2>&1 || true
+        docker kill  $DNS_CONTAINER_NAME        >/dev/null 2>&1 || true
+        docker kill  $RENDEZVOUS_CONTAINER_NAME >/dev/null 2>&1 || true
+        docker rm -f $CONTAINER_NAME            >/dev/null 2>&1 || true
+        docker rm -f $DNS_CONTAINER_NAME        >/dev/null 2>&1 || true
+        docker rm -f $RENDEZVOUS_CONTAINER_NAME >/dev/null 2>&1 || true
         run_tool host conntrack -D -p udp --dport $PORT >/dev/null 2>&1 || true
         destroy_bridge
         for LOCAL_IFNAME in $(ip link show | grep v${CONTAINER_IFNAME}pl | cut -d ' ' -f 2 | tr -d ':') ; do
