bump docker version requirement for `--with-dns` and explain why
Fixes #587.

diff --git a/weave b/weave
--- a/weave
+++ b/weave
@@ -517,8 +517,12 @@ wait_for_status() {
 dns_args() {
     if [ \( "$DOCKER_VERSION_MAJOR" -lt 1 \) -o \
         \( "$DOCKER_VERSION_MAJOR" -eq 1 -a \
-        "$DOCKER_VERSION_MINOR" -lt 2 \) ] ; then
-        echo "ERROR: The '--with-dns' option requires Docker 1.2.0 or later; you are running $DOCKER_VERSION" >&2
+        "$DOCKER_VERSION_MINOR" -lt 3 \) ] ; then
+        # Versions prior to 1.2.0 cannot parse `--dns-search=.`, and
+        # versions prior to 1.3.0 fail to include the domain when
+        # setting the hostname, so lookups for non-fully-qualified
+        # names fail.
+        echo "ERROR: The '--with-dns' option requires Docker 1.3.0 or later; you are running $DOCKER_VERSION" >&2
         exit 1
     fi
     docker_bridge_ip
