Show expected error message when docker_tls_args fails.
And also make the error message more meaningful.

Fixes #1843.

diff --git a/weave b/weave
--- a/weave
+++ b/weave
@@ -1456,9 +1456,13 @@ proxy_args() {
     proxy_parse_args "$@"
 
     if [ -z "$PROXY_TLS_ENABLED" ] ; then
-      if [ -z "$PROXY_TLS_DETECTION_DISABLED" ] && ! proxy_parse_args $(docker_tls_args) ; then
-        echo "Unable to auto-detect TLS configuration, --no-detect-tls or TLS options are required." >&2
-        exit 1
+      if [ -z "$PROXY_TLS_DETECTION_DISABLED" ] ; then
+          if ! DOCKER_TLS_ARGS=$(docker_tls_args) ; then
+              echo "Unable to auto-detect proxy TLS configuration; you must launch the proxy with" >&2
+              echo "'weave launch-proxy' and supply '--no-detect-tls' or TLS options." >&2
+              exit 1
+          fi
+          proxy_parse_args "$DOCKER_TLS_ARGS"
       fi
     fi
     if [ -z "$PROXY_HOST" ] ; then
