fix create_bridge() bug, patch README install recipe, WEAVE_DOCKER_ARGS=''

diff --git a/weaver/weave b/weaver/weave
--- a/weaver/weave
+++ b/weaver/weave
@@ -29,9 +29,11 @@ command_exists () {
 
 [ $# -gt 0 ] || usage
 
+WEAVE_IMAGE='zettio/weave'
 BRIDGE=weave
 CONTAINER_IFNAME=ethwe
 MTU=65535
+WEAVE_DOCKER_ARGS=''
 
 COMMAND=$1
 
@@ -75,7 +77,7 @@ add_nat_rule() {
 
 create_bridge() {
     [ ! -d /sys/class/net/$BRIDGE ] && {
-        ip link add dev $BRIDGE type bridge
+        ip link add name $BRIDGE type bridge
         ip link set dev $BRIDGE address 7a:$(od -txC -An -N5 /dev/random | tr \  : | tail -c+2)
         # Attempting to set the bridge MTU to a high value directly
         # fails. Bridges take the lowest MTU of their interfaces. So
@@ -229,11 +231,11 @@ case "$COMMAND" in
         IPADDR=$1
         shift 1
         case $(docker inspect --format '{{ .State.Running }} {{ .Config.Image }}' weave 2>/dev/null) in
-            "true zettio/weave")
+            "true $WEAVE_IMAGE")
                 echo "Weave is already running." >&2
                 exit 1
                 ;;
-            "false zettio/weave")
+            "false $WEAVE_IMAGE")
                 docker rm weave >/dev/null
                 ;;
             true*)
@@ -255,7 +257,7 @@ case "$COMMAND" in
         # (eth0, wlan0, etc) so the name becomes stable across host
         # restarts.
         MACADDR=`cat /sys/class/net/$BRIDGE/address`
-        CONTAINER=$(docker run --privileged -d --name=weave -p 6783:6783/tcp -p 6783:6783/udp $WEAVE_DOCKER_ARGS zettio/weave -name $MACADDR "$@")
+        CONTAINER=$(docker run --privileged -d --name=weave -p 6783:6783/tcp -p 6783:6783/udp $WEAVE_DOCKER_ARGS $WEAVE_IMAGE -name $MACADDR "$@")
         with_container_netns attach $CONTAINER $IPADDR eth0
         echo $CONTAINER
         ;;
@@ -280,8 +282,8 @@ case "$COMMAND" in
     version)
         # Try the running container first; if no luck try the image
         if ! DOCKERIMAGE=$(docker inspect --format='{{ .Image }}' weave 2>/dev/null) ; then
-            if ! DOCKERIMAGE=$(docker inspect --format='{{ .Id }}' zettio/weave 2>/dev/null) ; then
-                echo "Unable to find zettio/weave image." >&2
+            if ! DOCKERIMAGE=$(docker inspect --format='{{ .Id }}' $WEAVE_IMAGE 2>/dev/null) ; then
+                echo "Unable to find $WEAVE_IMAGE image." >&2
                 exit 1
             fi
         fi
