cosmetic

diff --git a/weaver/weave b/weaver/weave
--- a/weaver/weave
+++ b/weaver/weave
@@ -124,13 +124,13 @@ configure_container_networking() {
     rm -f $IP_TMPFILE
     if ip link add name $LOCAL_IFNAME mtu $MTU type veth peer name $GUEST_IFNAME mtu $MTU >$IP_TMPFILE 2>&1 ; then
         if  (ip link set $LOCAL_IFNAME master $BRIDGE &&
-            ip link set $LOCAL_IFNAME up &&
-            ip link set $GUEST_IFNAME netns $NSPID) >$IP_TMPFILE 2>&1
+                ip link set $LOCAL_IFNAME up &&
+                ip link set $GUEST_IFNAME netns $NSPID) >$IP_TMPFILE 2>&1
         then
             (ip netns exec $NSPID ip link set $GUEST_IFNAME name $CONTAINER_IFNAME &&
-            ip netns exec $NSPID ip addr add $2 dev $CONTAINER_IFNAME &&
-            ip netns exec $NSPID ip link set $CONTAINER_IFNAME up &&
-            check_command_and_run ethtool ip netns exec $NSPID ethtool -K $3 tx off >/dev/null) >$IP_TMPFILE 2>&1 &&
+                ip netns exec $NSPID ip addr add $2 dev $CONTAINER_IFNAME &&
+                ip netns exec $NSPID ip link set $CONTAINER_IFNAME up &&
+                check_command_and_run ethtool ip netns exec $NSPID ethtool -K $3 tx off >/dev/null) >$IP_TMPFILE 2>&1 &&
             EXITCODE=0
         else
             # failed before we assigned the veth to the container's namespace - delete it
@@ -142,7 +142,7 @@ configure_container_networking() {
         if ! ps -p $DOCKERPID >/dev/null 2>&1 ; then
             echo "Container $1 died" >&2
         else
-            echo "Failure during network set-up:" >&2
+            echo "Failure during network configuration for container $1:" >&2
             cat $IP_TMPFILE >&2
         fi
     fi
